name: Paratranz到GitHub

on:
  schedule:
    # 每天北京时间早上9点和晚上9点运行
    - cron: "0 1,13 * * *"
  workflow_dispatch:

jobs:
  paratranz-to-gitHub:
    name: Paratranz到GitHub
    environment: PARATRANZ_ENV
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_ID: ${{ vars.ID }}
    outputs:
      changed: ${{ steps.commit.outputs.changed }} # 定义输出变量
    steps:
      - uses: actions/checkout@v4
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: 安装依赖项
        run: |
          pip install requests
          pip install nbtlib
      - name: 配置Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "[BOT]"
      - name: 结帐主分支
        run: git checkout main
      - name: Paratranz到GitHub
        run: python .github/workflows/para2github.py
      - name: 提交更改
        id: commit
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m '从Paratranz同步翻译'
            git push origin main
            echo "changed=true" >> $GITHUB_OUTPUT # 使用 $GITHUB_OUTPUT 设置输出
            echo "译文变动，发布release！"
          else
            echo "changed=false" >> $GITHUB_OUTPUT # 使用 $GITHUB_OUTPUT 设置输出
            echo "译文不变，取消发布release！"
          fi
  release:
    name: 创建发布
    runs-on: ubuntu-latest
    environment: PARATRANZ_ENV
    needs: paratranz-to-gitHub
    if: ${{ needs.paratranz-to-gitHub.outputs.changed == 'true' }}
    steps:
      - name: 结帐
        uses: actions/checkout@v4
      - name: Upload CNPack folder
        uses: actions/upload-artifact@v4
        with:
          name: CNPack
          path: ${{ github.workspace }}/CNPack
      - name: 获取标签的当前日期时间
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Zip CNPack文件夹
        run: zip -r "${{ env.datetime }}.zip" ./CNPack
      - name: 上传神器
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.datetime }}.zip"
          path: "${{ env.datetime }}.zip"
      - name: 创建发布
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.datetime }}.zip"
          tag: "Release-${{ env.datetime }}"
          name: "Release ${{ env.datetime }}"
          body: "自动生成的最新汉化补丁"
          draft: false
          prerelease: true
